"""init

迁移 ID: 775297f44083
父迁移:
创建时间: 2025-01-11 21:12:49.406798

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "775297f44083"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kuro_kurotoken",
        sa.Column("kuro_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("basic_info", sa.JSON(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["nonebot_plugin_uninfo_usermodel.id"],
            name=op.f("fk_kuro_kurotoken_user_id_nonebot_plugin_uninfo_usermodel"),
        ),
        sa.PrimaryKeyConstraint("kuro_id", name=op.f("pk_kuro_kurotoken")),
        info={"bind_key": "kuro"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kuro_kurotoken")
    # ### end Alembic commands ###
