"""update

迁移 ID: 0c96e0e74726
父迁移: 7c9dbbd5d73d
创建时间: 2024-11-19 11:19:41.159856

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "0c96e0e74726"
down_revision: str | Sequence[str] | None = "7c9dbbd5d73d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_pipe_msgidcache",
        sa.Column("src_adapter", sa.String(), nullable=False),
        sa.Column("src_id", sa.String(), nullable=False),
        sa.Column("dst_adapter", sa.String(), nullable=False),
        sa.Column("dst_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "src_adapter",
            "src_id",
            "dst_adapter",
            "dst_id",
            name=op.f("pk_group_pipe_msgidcache"),
        ),
        info={"bind_key": "group_pipe"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_pipe_msgidcache")
    # ### end Alembic commands ###
