"""init

迁移 ID: 7c9dbbd5d73d
父迁移:
创建时间: 2024-10-30 13:47:35.890745

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "7c9dbbd5d73d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_pipe_pipe",
        sa.Column("listen", sa.Integer(), nullable=False),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column("listen_t", sa.JSON(), nullable=False),
        sa.Column("target_t", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("listen", "target", name=op.f("pk_group_pipe_pipe")),
        info={"bind_key": "group_pipe"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_pipe_pipe")
    # ### end Alembic commands ###
