"""add kvcache

迁移 ID: c79483f13a77
父迁移: 0c96e0e74726
创建时间: 2024-11-20 14:14:33.957542

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c79483f13a77"
down_revision: str | Sequence[str] | None = "0c96e0e74726"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_pipe_kvcache",
        sa.Column("adapter", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expire", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("adapter", "key", name=op.f("pk_group_pipe_kvcache")),
        info={"bind_key": "group_pipe"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_pipe_kvcache")
    # ### end Alembic commands ###
