"""update

迁移 ID: e5dcf2150f81
父迁移: 2e39fdc3f6b1
创建时间: 2024-11-18 16:45:38.770989

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e5dcf2150f81"
down_revision: str | Sequence[str] | None = "2e39fdc3f6b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_pipe_msgidcache",
        sa.Column("src_adapter", sa.String(), nullable=False),
        sa.Column("src_id", sa.String(), nullable=False),
        sa.Column("dst_adapter", sa.String(), nullable=False),
        sa.Column("dst_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "src_adapter",
            "src_id",
            "dst_adapter",
            name=op.f("pk_group_pipe_msgidcache"),
        ),
        info={"bind_key": "group_pipe"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_pipe_msgidcache")
    # ### end Alembic commands ###
