[package]
name = "wplace_template_compare"
version = "0.1.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.25.8"
lazy_static = "1.5.0"
pyo3 = { version = "0.27.1", features = ["extension-module"] }

[package.metadata.maturin]
python-data = ["wplace_template_compare.py"]
