[project]
name = "wplace_template_compare"
version = "0.1.1"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["maturin>=0.14"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "maturin>=1.9.6",
]

[tool.maturin]
python-source = "python"
module-name = "wplace_template_compare._compare"
