FROM wyf7685/bot7685:base

WORKDIR /app

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

COPY ./docker/bot7685/fonts/*.ttf /usr/share/fonts/
RUN fc-cache -f -v

COPY . /app/
RUN uv sync

CMD [ "bash" ]
