FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN apt-get update \
    && apt-get install -y openbox curl unzip x11vnc xvfb fluxbox supervisor libnotify4 libnss3 xdg-utils libsecret-1-0 libgbm1 libasound2 fonts-wqy-zenhei git gnutls-bin \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
