from ..utils import lazy_import

_LOCATION = {
    # Requests
    "WuwaBaseDataRequest": "aki.roleBox.akiBox.baseData",
    "WuwaCalabashDataRequest": "aki.roleBox.akiBox.calabashData",
    "WuwaChallengeDetailsRequest": "aki.roleBox.akiBox.challengeDetails",
    "WuwaChallengeIndexRequest": "aki.roleBox.akiBox.challengeIndex",
    "WuwaExploreIndexRequest": "aki.roleBox.akiBox.exploreIndex",
    "WuwaGetAllRoleRequest": "aki.roleBox.akiBox.getAllRole",
    "WuwaGetRoleDetailRequest": "aki.roleBox.akiBox.getRoleDetail",
    "WuwaGetShowSettingsRequest": "aki.roleBox.akiBox.getShowSettings",
    "WuwaRefreshDataRequest": "aki.roleBox.akiBox.refreshData",
    "WuwaRoleDataRequest": "aki.roleBox.akiBox.roleData",
    "WuwaSkinDataRequest": "aki.roleBox.akiBox.skinData",
    "WuwaTowerDataDetailRequest": "aki.roleBox.akiBox.towerDataDetail",
    "WuwaTowerIndexRequest": "aki.roleBox.akiBox.towerIndex",
    "WuwaUpdateShowRoleSettingRequest": "aki.roleBox.akiBox.updateShowRoleSetting",
    "WuwaUpdateShowSettingRequest": "aki.roleBox.akiBox.updateShowSetting",
    "GetSdkLoginUrlRequest": "config.dict.getSdkLoginUrl",
    "TimingSwitchRequest": "config.dict.timingSwitch",
    "GetOpenScreenRequest": "config.getOpenScreen",
    "GetGoldLogsRequest": "encourage.gold.getGoldLogs",
    "GetTotalGoldRequest": "encourage.gold.getTotalGold",
    "InitSigninV2Request": "encourage.signIn.initSignInV2",
    "QueryRecordV2Request": "encourage.signIn.queryRecordV2",
    "SigninV2Request": "encourage.signIn.v2",
    "IsRedPointRequest": "forum.dynamic.isRedPoint",
    "RoleDefaultRequest": "gamer.role.default",
    "RoleListRequest": "gamer.role.list",
    "PnsRoleListRequest": "gamer.role.list",
    "WuwaRoleListRequest": "gamer.role.list",
    "QueryUserIdRequest": "gamer.role.queryUserId",
    "WuwaWidgetGetDataRequest": "gamer.widget.game3.getData",
    "UserCenterInitRequest": "user.center.init",
    "GetSmsCodeRequest": "user.getSmsCode",
    "UserLoginLogRequest": "user.login.log",
    "MineV2Request": "user.mineV2",
    "FindRoleListRequest": "user.role.findRoleList",
    "SdkLoginRequest": "user.sdkLogin",
    "SdkLoginForH5Request": "user.sdkLoginForH5",
    "SdkLogoutRequest": "user.sdkLogout",
    "SignInRequest": "user.signIn",
    "SignInInfoRequest": "user.signInInfo",
    # Models
    "Phantom": "aki.roleBox.akiBox.getRoleDetail",
    "PhantomAttribute": "aki.roleBox.akiBox.getRoleDetail",
    "RoleDetail": "aki.roleBox.akiBox.getRoleDetail",
    "PnsRole": "gamer.role.list",
    "Role": "gamer.role.list",
    "WuwaRole": "gamer.role.list",
    "Mine": "user.mineV2",
}

lazy_import(_LOCATION)
