"""Stable public contracts for Bot7685 LLM consumers."""

from .config import (
    AnthropicThinkingConfig,
    EndpointConfig,
    EndpointProtocol,
    LLMConfig,
    ModelConfig,
)
from .exceptions import (
    LLMCapabilityError,
    LLMConfigurationConflictError,
    LLMConfigurationError,
    LLMErrorCategory,
    LLMModelSelectionError,
    LLMRunError,
    LLMServiceError,
)
from .models import (
    AgentLimits,
    AgentRunResult,
    AgentTrace,
    ChatInput,
    ChatInputPart,
    ImagePart,
    ModelCallTrace,
    ModelCapabilities,
    ModelCapability,
    ModelInfo,
    ReasoningEffort,
    RunResult,
    StructuredOutputFallbackReason,
    StructuredOutputMode,
    StructuredRunResult,
    TextPart,
    ToolCallTrace,
    ToolErrorCategory,
)
from .service import LLMConfigurationSnapshot, LLMService, get_llm_service
from .tools import (
    BoundTool,
    JSONObject,
    JSONScalar,
    JSONValue,
    ToolArgumentsError,
    ToolImageAttachment,
    ToolOutput,
    ToolOutputSerializationError,
    ToolOutputTooLargeError,
)
from .usage import CompletionTokensDetails, PromptTokensDetails, TokenUsage

__all__ = [
    "AgentLimits",
    "AgentRunResult",
    "AgentTrace",
    "AnthropicThinkingConfig",
    "BoundTool",
    "ChatInput",
    "ChatInputPart",
    "CompletionTokensDetails",
    "EndpointConfig",
    "EndpointProtocol",
    "ImagePart",
    "JSONObject",
    "JSONScalar",
    "JSONValue",
    "LLMCapabilityError",
    "LLMConfig",
    "LLMConfigurationConflictError",
    "LLMConfigurationError",
    "LLMConfigurationSnapshot",
    "LLMErrorCategory",
    "LLMModelSelectionError",
    "LLMRunError",
    "LLMService",
    "LLMServiceError",
    "ModelCallTrace",
    "ModelCapabilities",
    "ModelCapability",
    "ModelConfig",
    "ModelInfo",
    "PromptTokensDetails",
    "ReasoningEffort",
    "RunResult",
    "StructuredOutputFallbackReason",
    "StructuredOutputMode",
    "StructuredRunResult",
    "TextPart",
    "TokenUsage",
    "ToolArgumentsError",
    "ToolCallTrace",
    "ToolErrorCategory",
    "ToolImageAttachment",
    "ToolOutput",
    "ToolOutputSerializationError",
    "ToolOutputTooLargeError",
    "get_llm_service",
]
