"""Stable LLM configuration, runtime, service, and agent contracts."""

from .config import EndpointConfig, LLMConfig, ModelCapabilities, ModelConfig
from .conversation import (
    AgentCompletionBackend,
    AgentHistoryItem,
    AgentModelCapabilities,
    AgentModelTurn,
    AgentToolCall,
    AgentToolResult,
    run_agent,
)
from .exceptions import (
    LLMCapabilityError,
    LLMConfigurationError,
    LLMErrorCategory,
    LLMModelSelectionError,
    LLMRunError,
    LLMServiceError,
)
from .models import (
    AgentLimits,
    AgentRunResult,
    AgentTrace,
    ChatInput,
    ChatInputPart,
    ImagePart,
    ModelCallTrace,
    ModelInfo,
    RunResult,
    StructuredOutputFallbackReason,
    StructuredOutputMode,
    StructuredRunResult,
    TextPart,
    ToolCallTrace,
    ToolErrorCategory,
)
from .runtime import LLMRuntime, ModelHandle
from .service import LLMService, get_llm_service
from .tools import (
    BoundTool,
    JSONObject,
    JSONScalar,
    JSONValue,
    ToolArgumentsError,
    ToolDefinition,
    ToolOutput,
    ToolOutputSerializationError,
    ToolOutputTooLargeError,
)
from .usage import CompletionTokensDetails, PromptTokensDetails, TokenUsage

__all__ = [
    "AgentCompletionBackend",
    "AgentHistoryItem",
    "AgentLimits",
    "AgentModelCapabilities",
    "AgentModelTurn",
    "AgentRunResult",
    "AgentToolCall",
    "AgentToolResult",
    "AgentTrace",
    "BoundTool",
    "ChatInput",
    "ChatInputPart",
    "CompletionTokensDetails",
    "EndpointConfig",
    "ImagePart",
    "JSONObject",
    "JSONScalar",
    "JSONValue",
    "LLMCapabilityError",
    "LLMConfig",
    "LLMConfigurationError",
    "LLMErrorCategory",
    "LLMModelSelectionError",
    "LLMRunError",
    "LLMRuntime",
    "LLMService",
    "LLMServiceError",
    "ModelCallTrace",
    "ModelCapabilities",
    "ModelConfig",
    "ModelHandle",
    "ModelInfo",
    "PromptTokensDetails",
    "RunResult",
    "StructuredOutputFallbackReason",
    "StructuredOutputMode",
    "StructuredRunResult",
    "TextPart",
    "TokenUsage",
    "ToolArgumentsError",
    "ToolCallTrace",
    "ToolDefinition",
    "ToolErrorCategory",
    "ToolOutput",
    "ToolOutputSerializationError",
    "ToolOutputTooLargeError",
    "get_llm_service",
    "run_agent",
]
