"""first revision

迁移 ID: 619ac704cff8
父迁移:
创建时间: 2024-09-14 14:31:43.468487

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "619ac704cff8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("skland_sign",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skland_sign_arkaccount",
        sa.Column("uid", sa.String(length=16), nullable=False),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_skland_sign_arkaccount")),
        sa.UniqueConstraint("uid"),
        info={"bind_key": "skland_sign"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skland_sign_arkaccount")
    # ### end Alembic commands ###
