"""init db

迁移 ID: 4e22438c2c74
父迁移:
创建时间: 2024-07-18 13:39:47.542491

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = "4e22438c2c74"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("upload_cos",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_cos_cosuploadfile",
        sa.Column("key", sa.TEXT(), nullable=False),
        sa.Column("expire_at", sa.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_upload_cos_cosuploadfile")),
        info={"bind_key": "upload_cos"},
    )
    op.create_table(
        "upload_cos_cosuploadpermission",
        sa.Column("user_id", sa.TEXT(), nullable=False),
        sa.Column("expire_at", sa.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint(
            "user_id", name=op.f("pk_upload_cos_cosuploadpermission")
        ),
        info={"bind_key": "upload_cos"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upload_cos_cosuploadpermission")
    op.drop_table("upload_cos_cosuploadfile")
    # ### end Alembic commands ###
