name: Lint

on:
  push:
    paths:
      - "src/**"
      - "bot.py"
      - ".github/workflows/lint.yml"
      - "pyproject.toml"
      - "uv.lock"
      - "ruff.toml"
      - "ty.toml"

jobs:
  ruff:
    name: ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          src: >-
            src/
            bot.py

  ty:
    name: ty Lint
    runs-on: ubuntu-latest
    needs: ruff
    concurrency:
      group: ty-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Run ty
        run: uv run ty check .
